### ISSUE TITLE
Rename t6_semaphore_wait_on_zero and t6_semaphore_wait_on_max for clarity

### ISSUE THREAD

**Issue by skotaracTT** [tenstorrent/tt-llk#71]
Function `t6_semaphore_wait_on_zero(const uint8_t index)` is used to wait while semaphore is 0 i.e while `sem == 0`. However this is counter intuitive since "wait on zero" suggests we wait for semaphore to be 0 i.e wait while `sem != 0`.  Similarly for `t6_semaphore_wait_on_max`, the name implies waiting until the semaphore reaches its maximum value i.e while `sem!= max` or `sem < max`, but it in fact waits while `sem == max` which could lead to confusion.

```cpp
template <uint WaitRes>
inline void t6_semaphore_wait_on_max(const uint8_t index)
{
    TTI_SEMWAIT(WaitRes, semaphore::t6_sem(index), p_stall::STALL_ON_MAX);
}

template <uint WaitRes>
inline void t6_semaphore_wait_on_zero(const uint8_t index)
{
    TTI_SEMWAIT(WaitRes, semaphore::t6_sem(index), p_stall::STALL_ON_ZERO);
}
```

Notice that our `wait_sem_cond` for `TTI_SEMWAIT` is `STALL_ON_ZERO` and `STALL_ON_MAX`, there respective values are shown below.
```cpp
//ckernel_instr_params.h
constexpr static uint STALL_ON_ZERO = 0x1;
constexpr static uint STALL_ON_MAX  = 0x2;
```
However, we can see that `SEMWAIT` will acknowledge that passing argument wait_sem_cond is 1 i.e `STALL_ON_ZERO` then it waits while semaphore is 0 and when `wait_sem_cond` is 2 i.e `STALL_ON_MAX` it waits while semaphore is max.
```yaml
SEMWAIT:
    instrn_type: LOCAL_CREGS
    ex_resource: SYNC
    op_binary: 0xa6
    src_mask: 0x0
    fcov:
    arguments:
        - name: wait_sem_cond
          start_bit: 0
          field_type: DEC
          description: "Wait on semaphore. 1 - wait while semaphore is 0, 2 - wait while semaphore is max"
          fcov_point_bins:
            bins: [ {name: "WaitWhileZero",    value: "0x1"},
                    {name: "WaitWhileMax",  value: "0x2"}]
```

Renaming the functions to `t6_semaphore_wait_while_zero` and `t6_semaphore_wait_while_max` would more accurately reflect its purpose. It clearly indicates that the function is waiting while the semaphore value is zero, not until it reaches zero. This change would make the code more intuitive for developers who read the function name and try to understand its behavior at a glance.
